### ISSUE TITLE
Fix Unit test failures

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-multisite#1]
## Issue Overview

There are a bunch of unit test failures. I only noticed them today (after the release of EE core 4.10) but they seem to have existed since before then. We just hadn't noticed them from the nightly builds. Eg https://travis-ci.com/eventespresso/eea-multisite/jobs/218461559
Fixing these would be nice in order to confirm there's no actual problem, and to make it more clear if there is a problem introduced in the future.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Steps to Reproduce (for bugs)

Run the multisite tests locally (or refer to the latest nightly builds on Circle). There are a lot of unit test failures.

**Comment by mnelson4** [comment]
Passing to Josh for triaging. This may be a fairly easy fix.

**Comment by mnelson4** [comment]
On #5 I noticed the current errors are because some code was deprecated in WP 5.1. (So, this ticket was originally for some OTHER failures, which we apparently resolved but forgot to close this ticket. Now it's for the current test failures caused by WP 5.1)

**Comment by joshfeck** [comment]
I tested this and verified that the new entry was made in wp_esp_blog_meta for the new site.

**Comment by mnelson4** [comment]
I just checked and there are no unit test failures in multisite master now
