### ISSUE TITLE
Migrate active sites only

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-multisite#2]
**Summary**
The migration tool started failing after about 16k sites. I refreshed like it suggested and it gets another batch of records and then errors out again. I haven't been able to get it to finish up.

I checked some of the sites and I noticed they are spam or archived sites.

Here are a couple of examples:

- https://soccernight.eventsmart.com
- https://ejmevents.eventsmart.com

Could we adjust the tool so it looks for active sites only?

**Comment by knazart** [comment]
Just a note worth mentioning: 
Brad from Pagely team did mention that their script on updating the WP version through the network went through `16221` sites, so I assume that's the number of live sites, thus it's likely that the tool started failing when it hit the archived sites but did manage to update all (or most) of the live sites.

**Comment by mnelson4** [comment]
> Could we adjust the tool so it looks for active sites only?

Yeah that's quite easy. The tricky part is when an archived site gets restored. We'll need to THEN migrate them, and currently that would require a network admin visiting the site and migrating it manually.

**Comment by lorenzocaum** [comment]
Hey Mike, we could handle that and if their site has been archived then they haven't used Event Smart for a long time.

@garthkoyle Can you remember any customers reaching out after their site has been closed?

I've seen a few requests to not archive as replies to the notification emails but I can't recall anyone asking after it has happened already.

**Comment by garthkoyle** [comment]
@lorenzocaum No, I have not had anyone request to **re-activate** their site.
